chat/urls.py
from django.urls import path

from . import views


app_name='chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/',views.login, name='login'),
    path('chatting/',views.chatting, name='chatting'),
    path('sending/',views.sending, name='sending'),
    path('setuser/',views.setuser, name='setuser'),
    path('getmsgs/',views.getmsgs, name='getmsgs'),
   ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('chat/', include('chat.urls')),
]

chat/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    user_name=models.CharField(max_length=200)
    password=models.CharField(max_length=200)
    active=models.BooleanField(default=False)

    def __str__(self):
        return self.user_name

class Mesg(models.Model):
    msg_text=models.CharField(max_length=400)
    is_read=models.BooleanField(default=True)
    from_user=models.ForeignKey(User, on_delete=models.CASCADE,related_name='sentfrom',default=1)
    to_user=models.ForeignKey(User, on_delete=models.CASCADE,related_name='sentto',default=1)

    def __str__(self):
        return self.msg_text

    

chat/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from .models import User,Mesg
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse


# Create your views here.

def index(request):
  
    '''
    view func for main index page
    '''
    #remove all temporary session data
    request.session.flush()
    #load html template
    template = loader.get_template('chat/index.html')
    #empty context
    context = {}
    #render html template and return response
    return HttpResponse(template.render(context, request))

@csrf_exempt
def setuser(request):
     '''
     post api to change second user
     '''
     if request.POST:
       #set second user value in session to clicked user value  
       request.session['user2']=request.POST['user']   
       #redirect to chatting page
       return HttpResponseRedirect(reverse('chat:chatting', args=()))

 
def getmsgs(request):
    '''
     view func to return all unread msgs
     
    '''
    #get both users msgs
    user1_msgs=[]
    user2_msgs=[]

    #get user objects
    user1=User.objects.get(user_name=request.session['user1'])
    user2=User.objects.get(user_name=request.session['user2'])

    #check if user a selected a second user to chat or not
    if request.session['user2']!=request.session['user1']:

     #get msgs sent by user1 to user2   
     for msg in Mesg.objects.filter(from_user=user1,to_user=user2,is_read=False):
        user1_msgs.append(msg.msg_text)
        msg.is_read=True
        msg.save()


     #get msgs sent by user2 to user1
     for msg in Mesg.objects.filter(from_user=user2,to_user=user1,is_read=False):
        user2_msgs.append(msg.msg_text)
        msg.is_read=True
        msg.save()
     
    #render and return html template     
    template = loader.get_template('chat/latest_msgs.html')
    context = {'user1':request.session['user1'].upper(),'user2':request.session['user2'].upper(),'user1_msgs':user1_msgs,'user2_msgs':user2_msgs}
    return HttpResponse(template.render(context, request))

def chatting(request):
    '''
     view func to display main chatting page
    '''
    #list to maintain all signed in users
    users_active=[]

    #get all active users from DB
    for user in User.objects.filter(active=True):
        users_active.append(user.user_name)
    
    #get both users msgs
    user1_msgs=[]
    user2_msgs=[]

    #get user objects
    user1=User.objects.get(user_name=request.session['user1'])
    user2=User.objects.get(user_name=request.session['user2'])
    

    #check if user a selected a second user to chat or not
    if request.session['user2']!=request.session['user1']:

     #get msgs sent by user1 to user2   
     for msg in Mesg.objects.filter(from_user=user1,to_user=user2):
        user1_msgs.append(msg.msg_text)

     #get msgs sent by user2 to user1   
     for msg in Mesg.objects.filter(from_user=user2,to_user=user1):
        user2_msgs.append(msg.msg_text)

    #render and return html template     
    template = loader.get_template('chat/chatting.html')
    context = {'users':users_active, 'user1':request.session['user1'].upper(),'user2':request.session['user2'].upper(),'user1_msgs':user1_msgs,'user2_msgs':user2_msgs}
    return HttpResponse(template.render(context, request))

def sending(request):
    '''
    post api for receiving new text message
    '''
    if request.POST:
        #get current msg
        msg = request.POST['newmsg']
        #get both users
        user=User.objects.get(user_name=request.session['user1'])
        user2=User.objects.get(user_name=request.session['user2'])
        #save new msg to db 
        new_msg=Mesg(msg_text=msg,from_user=user,to_user=user2,is_read=False)
        new_msg.save()  
         
    #redirect to same page    
    return HttpResponseRedirect(reverse('chat:chatting', args=()))

def login(request):
    '''
    view func for logging current user using username and pass
    '''
    #if its a post request from client
    if request.POST:
        #reading username and password from request object
        username = request.POST['Uname']
        password = request.POST['Pass']

        #get current user from DB
        current_user=User.objects.filter(user_name=username,password=password).count()

        #if correct credentials
        if current_user==1:
            #save current user to session object
            request.session['user1']=username
            request.session['user2']=username
            request.session.modified = True

            #add user to online users
            u=User.objects.get(user_name=username,password=password)
            u.active=True
            u.save()
            
            #redirect to chatting page
            return HttpResponseRedirect(reverse('chat:chatting', args=()))

        else:
            #redirect to main index page with error shown
            template = loader.get_template('chat/index.html')
            context = {'error':'1'} 
            return HttpResponse(template.render(context, request))

    

chat/templates/chat/chatting.html
<!DOCTYPE html>
<html>

<head>
  <meta>
</head>
<style>
    * {
    margin: 0;
    padding: 0;
    font-family: 'Nunito', sans-serif;
  }
  
  html, body {
    background-color:rgba(1, 36, 4, 0.865);
    overflow: hidden;
  }
  
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 106vh;
    width: 100vw;
   
  }
  
  .chatbox {
    background: rgba(255, 255, 255, 0.05);
    width: 98%;
    height: 70%;
    border-radius: 0.2em;
    position: relative;
    box-shadow: 1px 1px 12px rgba(0, 0, 0, 0.1);
    overflow-y:scroll;
  }
  

  

  .chatbox__user-list {
    background: rgba(255, 255, 255, 0.1);
    width: 23%;
    height: 100%;
    float: left;
    border-top-right-radius: 0.2em;
    border-bottom-right-radius: 0.2em;
    cursor: pointer;
  
  }
  
  .chatbox__user-list h1 {
    background: rgba(255, 255, 255, 0.05);
    color: black;
    font-size: 0.9em;
    padding: 1em;
    margin: 0;
    font-weight: 300;
    text-align: center;

  }
  
  .chatbox__user, .chatbox__user--active, .chatbox__user--away {
    width: 0.5em;
    height: 0.5em;
    border-radius: 100%;
    margin: 1em 0.7em;
  }

  .chatbox__messages{
    display: flex;
  flex-direction: column;
 
  }
  .chatbox__messages__user-message--ind-message-right {
    background: rgba(255, 255, 255, 0.2);
    padding: 1em 0;
    float:right;
    height: auto;
    width: auto;
    border-radius: 5px;
    margin: 2em 1em;
    
  }

  .chatbox__messages__user-message--ind-message-right > p.name {
    color: #FFF;
    font-size: 1em;
   
  }
  
  .chatbox__messages__user-message--ind-message-right > p.message {
    color: #FFF;
    font-size: 0.7em;
    margin: 0 2.8em;
   
  }
  
  .chatbox__messages__user-message--ind-message-left {
    background: rgba(255, 255, 255, 0.2);
    padding: 1em 0;
    float:left;
    height: auto;
    width: auto;
    border-radius: 5px;
    margin: 2em 1em;
    overflow: auto;
    
  }

  .chatbox__messages__user-message--ind-message-left > p.name {
    float: right;
    color: #FFF;
    font-size: 1em;
   
  }
  
  .chatbox__messages__user-message--ind-message-left > p.message {
    color: #FFF;
    float: right;
    font-size: 0.7em;
    margin: 0 2.8em;
  
  }
  
  
  .chatbox__user--active {
    background: rgba(23, 190, 187, 0.8);
  }
  
  
  .chatbox__user--away {
    background: rgba(255, 253, 130, 0.8);
  }
  
  .chatbox p {
    float: left;
    text-align: left;
    margin: -0.25em 2em;
    font-size: 0.7em;
    font-weight: 300;
    color: #FFF;
    width: auto;
    
  }
  
  .chatbox form {
    background: #222;
    
  }
  
  .container form input {
    float:none;
    background: rgba(187, 48, 48, 0.03);
    position:absolute;
    bottom: 0;
    right: 0;
    border: none;
    width: 75%;
    padding: 1.2em;
    color: rgba(255, 255, 255, 0.9);
    font-weight: 300;
    
  }

  #send_msg{  
    width: 150px;  
    height: 10px;  
    border: none;  
    margin: auto;  
    border-radius: 16px;  
    padding-left: 7px;  
    font-size: 15px;
    color: #f1f9f193;  
  
  
}  
</style>

<body>
    <div class='container'>
        <div class='chatbox'>
            <div class='chatbox__user-list' 
                <h1>Friends Online</h1>
                {% for usr in users %}
                <div class='chatbox__user--active' id={{usr}}>
                  <p>{{usr}}</p>
                </div>
                {% endfor %}    
            </div>
            <div class="chatbox__messages">
              {% for msg in user1_msgs %}
                <div class="chatbox__messages__user-message-right">
                    <div class="chatbox__messages__user-message--ind-message-right">
                        <p class="name">{{user1}}</p>
                        <br />
                        <p class="message">{{msg}}</p>
                    </div>
                </div>
                {% endfor %} 
                {% for msg in user2_msgs %}
                <div class="chatbox__messages__user-message-left">
                    <div class="chatbox__messages__user-message--ind-message-left">
                      <p class="name">{{user2}}</p>
                      <br />
                      <p class="message">{{msg}}</p>
                    </div>
                </div>
                {% endfor %} 
            </div>
        </div>
        <form id="sending" action="{% url 'chat:sending' %}"  method="post">
          {% csrf_token %}   
          <input type="text"  name="newmsg" id="newmsg" placeholder="Type Message">
          <input type="submit"  id="send_msg" value="Send">
      </form> 
    </div> 
</body>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $("div.chatbox__user--active").click(function(){
      var body="user="+this.id;
      let xhr = new XMLHttpRequest();
      xhr.open('POST', '/chat/setuser/',true);
      xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
      xhr.send(body);
      xhr.onload = function() {
  if (xhr.status != 200) { // analyze HTTP status of the response
    alert(`Error ${xhr.status}: ${xhr.statusText}`); // e.g. 404: Not Found
  } else { // show the result
    location.reload(); // response is the server response
  }
};    
       })
});
</script>
<script type="text/javascript">
  setInterval(function() {
      let xhr = new XMLHttpRequest();
      xhr.open('GET', '/chat/getmsgs/',true);
      xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
      xhr.send();
      xhr.onload = function() {
  if (xhr.status != 200) { 
    alert(`Error ${xhr.status}: ${xhr.statusText}`); 
  } else { // show the result
    $('.chatbox__messages').append(xhr.responseText);
  }
};   
}, 3000);
</script>

</html>

chat/templates/chat/index.html
<!DOCTYPE html>    
<html>    
<head>    
    <title>Login Form</title>
    <style>
body  
{  
    margin: 0;  
    padding: 0;  
    background-color:#3c0624ba;  
    font-family: 'Arial';  
}  
.login{  
        width: 382px;  
        overflow: hidden;  
        margin: auto;  
        margin: 20 0 0 450px;  
        padding: 80px;  
        background: #23463f;  
        border-radius: 12px ;  
          
}  
h2{  
    text-align: center;  
    color: #edaac4;  
    padding: 20px;  
}  
label{  
    color: #08ffd1;  
    font-size: 17px;  
}  
#Uname{  
    width: 300px;  
    height: 30px;  
    border: none;  
    border-radius: 3px;  
    padding-left: 8px;  
}  
#Pass{  
    width: 300px;  
    height: 30px;  
    border: none;  
    border-radius: 3px;  
    padding-left: 8px;  
      
}  
#log{  
    width: 300px;  
    height: 30px;  
    border: none;  
    border-radius: 17px;  
    padding-left: 7px;  
    font-size: 16px;
    color: #050605;  
  
  
}  
    </style>     
</head>    
<body>    
    <h2>Welcome to Chat Application</h2><br> 
    <div class="login">    
    <form id="login" action="{% url 'chat:login' %}"  method="post"> 
        {% csrf_token %}   
        <label><b>User Name     
        </b>    
        </label>    
        <input type="text" name="Uname" id="Uname" placeholder="Username">    
        <br><br>    
        <label><b>Password     
        </b>    
        </label>    
        <input type="Password" name="Pass" id="Pass" placeholder="Password">    
        <br><br>    
        <input type="submit" name="log" id="log" value="Login">       
        <br><br>  
        <label>
            {% if error %}
            <b></b>Incorrect Username or Password </b>  
            {% endif %}       
        </label>       
    </form>     
</div>    
</body>    
</html>     

chat/templates/chat/latest_msgs.html
              {% for msg in user1_msgs %}
                <div class="chatbox__messages__user-message-right">
                    <div class="chatbox__messages__user-message--ind-message-right">
                        <p class="name">{{user1}}</p>
                        <br />
                        <p class="message">{{msg}}</p>
                    </div>
                </div>
                {% endfor %} 
                {% for msg in user2_msgs %}
                <div class="chatbox__messages__user-message-left">
                    <div class="chatbox__messages__user-message--ind-message-left">
                      <p class="name">{{user2}}</p>
                      <br />
                      <p class="message">{{msg}}</p>
                    </div>
                </div>
                {% endfor %} 
         